### ISSUE TITLE
All collisions are broken

### ISSUE THREAD

**Issue by Norrox** [KenneyNL/Starter-Kit-3D-Platformer#10]
Hello!
Im opening this in 4.2.dev5 and on a MacBook Air m2.
When I open the project all the collisions are broken, this might not be an issue for this starterkit, this might be a bug in Godot.
But when I create new collision for this it works.
Looks something like this when I made new collisions. (The one above with yellow exclamation mark is the ones that comes with the starterkit for me, is this how you made it or have there been some error in my importing? :D
<img width="1042" alt="Screenshot 2023-09-23 at 10 20 10" src="https://github.com/KenneyNL/Starter-Kit-3D-Platformer/assets/13393087/628231fa-3d58-49ff-b938-ad454360e8f1">

**Comment by KenneyNL** [comment]
I'm not sure what causes this issue however the project was built using Godot 4.1.1, I recommend opening it using the same version to make sure there's no problems like the one you've encountered.
