### ISSUE TITLE
Default settings are too slow on integrated graphics

### ISSUE THREAD

**Issue by Calinou** [KenneyNL/Starter-Kit-3D-Platformer#12]
To ensure the demo runs well on low-end GPUs out of the box, please consider changing the default 3D MSAA to be disabled[^1], and use FXAA or TAA instead. The directional soft shadow quality filter setting should also be set to Low, or perhaps Medium (but note that TAA will hide the shadow dithering pattern during motion already).

- See https://github.com/godotengine/godot/issues/82644.

[^1]: Even 2× MSAA is very expensive on integrated graphics compared to FXAA/TAA. This is due to MSAA's high memory bandwidth requirements, yet integrated GPUs are constantly starved when it comes to memory bandwidth.

**Comment by KenneyNL** [comment]
Thanks for letting me know! I've adjusted the anti-aliasing to FXAA and changed the soft shadow quality to 'low'
